modules/infrahouse.com/main.tf
modules/infrahouse.com/outputs.tf
modules/infrahouse.com/terraform.tf
outputs.tf
route53.infrahouse.com.tf

I tend to forget a provider configuration. Putting all related stuff
into a module seems more reliable way.

Move infrahouse.com zone to a module

---

modules/jumphost/lambda_code.tf

An S3 object isn't available right away for clients. Often there is a
short delay. The local provisioner waits until the file is readable.

Wait until lambda archive is available

---

modules/jumphost/lambda_code.tf

ih-plan can assumer a role while downloading an object from S3. Use
that.
The GHA worker runs as a -github role, but the provider is configured to
assume the -admin role. The -github role can assume the -admin role.

Use ih-plan download to check s3 object

---

modules/jumphost/lambda_code.tf

The ARN includes a session name, which isn't a part of the role ARN. Do
some cutting.

Fix provider's role

---

modules/jumphost/lambda.tf

It looks like lambda started updating before the s3 object was done
creating.
```
module.jumphost.aws_lambda_function.update_dns: Modifying...
[id=update_dns]
module.jumphost.aws_s3_object.lambda_package: Provisioning with
'local-exec'...
```
Utilize indirect dependency.

Ensure s3 object is available for lambda

---

modules/jumphost/lambda.tf

A publick IP address lookup only takes 3 secods - there is no way to
squeeze all operations in the default 3 seconds timeout.

Bring back lambda timeout 30 sec

---

modules/jumphost/lambda.tf
modules/jumphost/main.tf
modules/jumphost/update_dns/main.py

Sometimes the describe_instances() result doesn't contain
PublicIPAddress. In that case, try to fetch the public IP from tags.
The tag is supposed to be set by the launching lifecycle hook.

Use Tags as method to discover PublicIPAddress

---

modules/release.infrahouse.com/bucket.tf
modules/release.infrahouse.com/cloudfront.tf

The access logs are collected in s3://infrahouse-release-logs/

Configure logging for release.infrahouse.com

---

modules/release.infrahouse.com/cloudfront.tf

The destination should be a bucket domain name, not the bucket name.

Fix logging destination

---

aws_iam_policy.tf
jumphost.tf
modules/instance_profile/main.tf
modules/instance_profile/variables.tf
modules/jumphost/main.tf
modules/jumphost/variables.tf
modules/release.infrahouse.com/outputs.tf

The policy allows read/write (well, all operations on the releases
bucket).
The policy is attached to the jumphost profile. In future it can be
attached to other roles (thinking about GitHub Actions CD)

Create a publisher policy

---

modules/jumphost/update_dns/main.py

Sometimes `ResourceRecords`  is missing in `ResourceRecordSets` leading
to error:
```
[ERROR] KeyError: 'ResourceRecords'
Traceback (most recent call last):
  File "/var/task/main.py", line 171, in lambda_handler
    add_record(
  File "/var/task/main.py", line 45, in add_record
    for rr in rr_set["ResourceRecords"]:
```

Check if ResourceRecords is present in Route53 response

---

modules/jumphost/lambda.tf

Why? The first invocation continues a lifecycle hook. The second lambda
invocation cannot suceed because a lifecycle hook token is not valid
anymore.
Alternatively, the lambda doesn't have to complete the LC hook action.
However I'd like to control the retry logic (if it's needed in future).

Do not retry update_dns()

---

modules/jumphost/data_sources.tf
modules/jumphost/main.tf
modules/jumphost/variables.tf

Two reasons:
* Cloudinit doesn't replace $RELEASE in a URL, so need to build url
* Avility to use other versions than jammy. Will be useful for OS
upgrades

Specify jumphost version via codename

---

aws_iam_role.infrahouse-toolkit-github.tf

The GitHub Actions worker will assume this role. The role will have
permissions to upload a debian package to the infrahouse debian
repository.

Add role infrahouse-toolkit-github

---

aws_iam_role.infrahouse-toolkit-github.tf

We want to allow access to AWS only from the branch main. So, StringEquals

Fix trust policy

---

modules/jumphost/data_sources.tf

It seems, puppet's facter has a problem with gzip-compressed userdata.
Can't confirm, `facter` is producing following error
```
[2023-07-31 02:52:15.279430 ] DEBUG Facter::LegacyFactFormatter -
Converting hash to pretty json
/opt/puppetlabs/puppet/lib/ruby/3.2.0/json/common.rb:406:in `to_json':
source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
from /opt/puppetlabs/puppet/lib/ruby/3.2.0/json/common.rb:406:in
`generate'
from /opt/puppetlabs/puppet/lib/ruby/3.2.0/json/common.rb:406:in
`pretty_generate'
from
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/facter/framework/formatters/legacy_fact_formatter.rb:63:in
`hash_to_facter_format'
from
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/facter/framework/formatters/legacy_fact_formatter.rb:26:in
`format_for_no_query'
from …
```

Try non-compressed userdata

---

modules/jumphost/data_sources.tf

terraform isn't happy
```
Error: creating EC2 Launch Template (lt-01a8ef96822b4b00b) Version:
InvalidUserData.Malformed: Invalid BASE64 encoding of user data.
status code: 400, request id:
0553ded3-4a8f-4f6d-90b8-a78e4c556053
```

Re-enable base64

---

route53.cicd.infrahouse.com.tf

The NS records of the subdomain should be created in a zone of the
parent, not in the subdomain's zone.
So, zone_id should be of infrahouse.com, not ci-cd.infrahouse.com

Fix zone where the NS records are created

---

aws_iam_role.infrahouse-com-github.tf

The role will be used by a GitHub Actions worker. It will publish
the infrahouse-com package the apt repo.

Add role infrahouse-com-gihub

---

aws_iam_role.puppet-code-github.tf

As long as there is a module for a github actions role, use it for
the puppet-code repo. The role name will change, this is intentional. I
want to test how role names unification works. I.e. which is better -
custom or patterned names.

Recreate role for puppet-code repo

---

jumphost.tf

jumphost stays in a way of migrating the service network - disabling it temporarily.

Delete jumphost during migration

---

release.infrahouse.com.tf

The bucket policy allows access to cloudfront. However, other roles need to publish packages. The IAM rtoles allow it. But the bucket policy did not. Fixing.
Some other role still don't have this access (infrahouse-toolkit) but I change them whem I have a opportunity to test.

Grant publishing roles access to publish packages.

---

aws_iam_role.infrahouse-toolkit-github.tf
release.infrahouse.com.tf

The role existed, but it was created from individual resources. Wrap it
in a module for more uniform role creation and to pass the role to
bucket admins in the debian repo.

Create role infrahouse-toolkit-github with module

---

aws_iam_role.infrahouse-toolkit-github.tf

The ih-tf-infrahouse-toolkit-github role needs more privileges besides
accessing the releases bucket. It also needs to read secrets for
authentication.

The re-attach package-publisher to ih-tf-infrahouse-toolkit-github

---

gha_runner.tf
jumphost.tf

The token will be used in jumphost, to register GitHub self hosted
runners.

Create secret for GitHub token

---

gha_runner.tf
jumphost.tf

The jumphost will perform a role of github_runner. For that it needs
GITHUB_TOKEN with managerunner access. Pass it and make it available for
root only.

Pass GitHub token to jumphost

---

registry.tf

I'm getting a weird CORS error in 0.7
```
POST /management/deploykey/infrahouse-bookstack-aws HTTP/1.1
X-Forwarded-For: 23.123.142.164
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Host: registry.infrahouse.com
X-Amzn-Trace-Id: Root=1-664fd265-7f9d22b3739dae9e74f069e0
Content-Length: 0
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br, zstd
referer: https://registry.infrahouse.com/management
origin: https://registry.infrahouse.com
dnt: 1
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
priority: u=1
cookie: q_auth_742...
```
```
HTTP/1.1 403 CORS Rejected - Invalid origin
content-length: 0
```
Not sure why tapir/quarkus doesn't respect …

Enable and configure CORS in tapir

---

registry.tf

Tapir generates a URL with an "s3:" prefix. Maybe that's why terraform uses AWS sdk to download the module instead of using the http URL.
```
│ Could not download module "ecs" (registry.tf:1) source code from
│ "s3::https://infrahou
```

Downgrade tapir to 0.6.0

---

registry.tf

The s3: prefix causes an AWS error. 
When a user doesn't have AWS config, Terraform complains. When it does, Terraform uses AWS SDK to download an archive instead of HTTP
```
commit c05220cde2f77f36e1ec865de26d357cafc0268c
Author: Pascal Euhus <pascal.euhus@gmx.de>
Date:   Fri Jan 5 10:07:36 2024 +0100
no need to prepend modules with s3://
diff --git a/src/main/java/api/Modules.java b/src/main/java/api/Modules.java
index 64380d6..d4036b3 100644
--- a/src/main/java/api/Modules.java
+++ b/src/main/java/api/Modules.java
@@ -79,8 +79,7 @@ public class Modules {
throws StorageException {
Module module = new Module(namespace, name, provider, version);
String path = StorageUtil.generateModuleStoragePath(module);
-    String signedUrl = storageService.getDownloadUrlForArtifact(path);
-    String …
```

Bump tapir to 0.7.0

---

vpn.tf

We want to let VPN cliens reach certain networks. For that, we push the management VPC network range to the VPN client configuration.

Add VPN routes

---

vpn.tf

Target group health check should give time to run puppet.

Increase ELB healthcheck grace period on VPN to 900 seconds

---

vpn.tf

t3a.nano can't run puppet anymore.
```
[  174.058938] cloud-init[1642]: {"action":"install","module_name":"infrahouse-profile","module_version":">= 0.1.0 < 1.0.0","result":"noop","version":"0.1.0"}
Starting [0;1;39mDownload data forâ¦led at package install time[0m...
[[0;32m  OK  [0m] Finished [0;1;39mDownload data forâ¦ailed at package install time[0m.
Starting [0;1;39mTime & Date Service[0m...
[[0;32m  OK  [0m] Started [0;1;39mTime & Date Service[0m.
```

Upgrade VPN to t3a.micro

---

selfdrivedb.app.tf

Let's encrypt calls `ListHostedZones`
```
An error occurred (AccessDenied) when calling the ListHostedZones operation: User: arn:aws:iam::493370826424:user/home-assitant is not authorized to perform: route53:ListHostedZones because no identity-based policy allows the route53:ListHostedZones action
```

Change to ListHostedZones
