infrahouse/aws-control-493370826424

- modules/infrahouse.com/main.tf
as per
https://repost.aws/knowledge-center/route53-resolve-dkim-text-record-error
> Fix long TXT

- jumphost.tf
- modules/infrahouse.com/outputs.tf
- modules/jumphost/lambda.tf
- modules/jumphost/update_dns/main.py
- modules/jumphost/variables.tf
* Adds an IP to the A record if the new instance is launching
* Removes the IP from the A record if the new instance is terminating
> Jumphost Lambda updates DNS

- modules/jumphost/lambda_code.tf
Build it manually, so it's more predictable.
> Fix the role again.

- modules/jumphost/update_dns/main.py
yet, it takes about two seconds - removing.
> We don't need get-caller-identity

- modules/release.infrahouse.com/index.html
Recommendation from
https://developer.chrome.com/docs/lighthouse/pwa/viewport/
> Add viewport tag

- modules/release.infrahouse.com/index.html
A recommendation from
https://developer.chrome.com/docs/lighthouse/seo/meta-description
> Add meta-description

- modules/release.infrahouse.com/bucket.tf
The policy should allow public access to all objects in the bucket.
> Set infrahouse-release policy

- modules/release.infrahouse.com/files/distributions
SignWith will make reprepro sign the repo.
> Add GPG signing configuration

- modules/release.infrahouse.com/gpg.tf
* Add storage for a GPG private key
* Generate and add a passphrase
The private key value should be generated externally and added manually.
> Add signing secrets

- modules/jumphost/main.tf
Strange problems with instance TCP availability.
> Bumping jumphost to t3a.micro

- service-network.tf
The remaining couple of subnets will be enough for now.
> Remove one public and one private network.

- jumphost.tf
- modules/jumphost/data_sources.tf
- modules/jumphost/variables.tf
- providers.tf
- requirements-ci.txt
- service-network.tf
- terraform.tfvars
- variables.tf
* set envrironment tag on all created resources
* pass environment as a puppet fact to the jumphost
> Configure environment tag

- .github/workflows/terraform-CD.yml
5 was conservative. even 10 mins is. but let's see where it breaks next
time.
> Bump terraform apply timeout to 10 minutes

- .github/workflows/terraform-CD.yml
- modules/cloud-init-config/data_sources.tf
- Pass a role to userdata
- Increase allowed terraform apply time to 60 minutes
> Fix role not being passed to cloud-init-config

- jumphost.tf
infrahouse-puppet-data contains hiera data.
> Install infrahouse-puppet-data on jumphost

- jumphost.tf
- release.infrahouse.com.tf
> Update management network

- Makefile
- aws_iam_role.ih-tf-github-control-admin.tf
- jumphost.tf
The role will manage this AWS account from infrahouse8/github-control
> Add role ih-tf-github-control-admin

- .github/workflows/terraform-CD.yml
- .github/workflows/terraform-CI.yml
pull requests - `continuous-integration`
main - `live`.
> Rename GitHub Actions environments

- registry.tf
weird CORS errors. Pin down further,
> Pin tapir to 0.6

- registry.tf
> Disable CORS again

- data_sources.tf
- release.infrahouse.com.tf
- vpn.tf
This is for me to be able to upload packages build on arm64
> Allow AWSAdministratorAccess upload packages

- modules/infrahouse.com/main.tf
Also, fail SPF check if not google.com
> Remove deprecated SPF record

- .github/workflows/terraform-CD.yml
- .github/workflows/terraform-CI.yml
- Makefile
- modules/infrahouse.com/main.tf
This is for Google search console
> Add verification record for infrahouse.com

- infrahouse-github-backup.tf
> Upgrade github-backup instance to t3a.small

- service-network.tf
The 3.0.0 version creates an S3 gateway endpoint
> Upgrade service-network module to 3.0.0

- jumphost.tf
- twindb-mail.tf
Downgrade the `jumphost` module version from `3.2.1` to `3.1.1`.
The change addresses compatibility issues with the existing infrastructure, as version `3.2.1` introduced changes that are not supported within the current environment. This approach ensures stability while further modifications are investigated.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> Create replication, use unencrypted EFS

- jumphost.tf
Update the `jumphost` module version from `3.1.1` to `3.2.1`.
This change is being made to utilize the latest features and improvements available in version `3.2.1`, which include the removal of replication and the use of an encrypted EFS, enhancing security and resource management in the infrastructure.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> Remove replication, use enc EFS
